var productDetails={
        'product101':{
            'productId' : 'product1',
            'productName': 'Watch Apple',
            'productDescription': 'Watch Discription 1',            'productCategory': 'watch',
            'productImg': 'https://img.freepik.com/premium-psd/smart-watch-series-6-mockup-front-view_1332-25542.jpg?w=740',            
            'productActualPrice': '90',            
            'productDiscountedPrice': '81',            
            'productOffer': '10',
            'productVendor': 'shubham',
        },
        'product102':{
            'productId' : 'product2',
            'productName': 'Watch Samsung',
            'productDescription': 'Watch Discription 2',          'productCategory': 'watch',           
            'productImg': 'https://img.freepik.com/premium-psd/smart-watch-series-6-mockup-front-view_1332-25542.jpg?w=740',         
            'productActualPrice': '190',            
            'productDiscountedPrice': '95',            
            'productOffer': '50',
            'productVendor': 'shubham',            
        },
        'product103':{
            'productId' : 'product3',
            'productName': 'Watch Oppo',
            'productDescription': 'Watch Discription 3',             'productCategory': 'watch',        
            'productImg': 'https://as1.ftcdn.net/v2/jpg/02/95/76/42/1000_F_295764233_fuwRvw5QfssDCCQICNkWhYBwAK2QYs04.jpg',         
            'productActualPrice': '100',            
            'productDiscountedPrice': '100',            
            'productOffer': '0',
            'productVendor': 'xyz',            
        },
    
    'product104':{
            'productId' : 'product4',
            'productName': 'Phone 1',
            'productDescription': 'Phone Discription 1',           'productCategory': 'mobile',          
            'productImg': 'https://img.freepik.com/premium-psd/smart-watch-series-6-mockup-front-view_1332-25542.jpg?w=740',            
            'productActualPrice': '90',            
            'productDiscountedPrice': '81',            
            'productOffer': '10',
            'productVendor': 'xyz',            
        },
        'product105':{
            'productId' : 'product5',
            'productName': 'Phone 5',
            'productDescription': 'Phone Discription 2',  
            'productCategory': 'mobile',                     
            'productImg': 'https://img.freepik.com/premium-psd/smart-watch-series-6-mockup-front-view_1332-25542.jpg?w=740',         
            'productActualPrice': '90',            
            'productDiscountedPrice': '81',            
            'productOffer': '10',
            'productVendor': 'shubham',            
        },
        'product106':{
            'productId' : 'product6',
            'productName': 'Phone 6', 
            'productCategory': 'mobile',                  
            'productDescription': 'Phone Discription 3',            
            'productImg': 'https://img.freepik.com/premium-psd/smart-watch-series-6-mockup-front-view_1332-25542.jpg?w=740',         
            'productActualPrice': '90',            
            'productDiscountedPrice': '81',            
            'productOffer': '10',      
            'productVendor': 'shubham',      
        } 
}